services:
  - type: web
    name: abhijay-portfolio
    runtime: static
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    domains:
      - abhijay.tech
      - www.abhijay.tech
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
